# jdbc:h2:C:\Users\Public\Alura\jpa\database
# 1234

SELECT * FROM CATEGORIAS;
SELECT * FROM PRODUCTOS;
SELECT * FROM CLIENTES;
SELECT * FROM PEDIDOS;
SELECT * FROM ITEMS_PEDIDO;

SELECT * FROM PEDIDOS;
SELECT * FROM ITEMS_PEDIDO;
SELECT * FROM CLIENTES;