INSERT INTO TABLA_DE_VENDEDORES # Incluyendo el primer vendedor
(MATRICULA, NOMBRE, PORCENTAJE_COMISION)
VALUES
('00233', 'Joan Geraldo de la Fonseca', 0.10);

INSERT INTO TABLA_DE_VENDEDORES # Incluyendo dos vendedores más
(MATRICULA, NOMBRE, PORCENTAJE_COMISION)
VALUES
 ('00235','Márcio Almeida Silva',0.08);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, PORCENTAJE_COMISION)
VALUES
('00236','Cláudia Morais',0.08);

UPDATE TABLA_DE_VENDEDORES SET PORCENTAJE_COMISION = 0.11 # Actualizando la información de los vendedores
WHERE MATRICULA = '00236';

UPDATE TABLA_DE_VENDEDORES SET NOME = 'Joan Geraldo de la Fonseca Junior'
WHERE MATRICULA = '00233';

DELETE FROM TABLA_DE_VENDEDORES WHERE MATRICULA = '00233'; # Eliminando un vendedor

DROP TABLE TABLA_DE_VENDEDORES; # Eliminando y modificando la tabla de vendedores

CREATE TABLE TABLA_DE_VENDEDORES
( MATRICULA varchar(5),
NOMBRE varchar(100),
PORCENTAJE_COMISION float,
FECHA_ADMISION date,
DE_VACACIONES bit);

ALTER TABLE TABLA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, FECHA_ADMISION, PORCENTAJE_COMISION, DE_VACACIONES) VALUES ('00235','Márcio Almeida Silva','2014-08-15',0.08,0);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, FECHA_ADMISION, PORCENTAJE_COMISION, DE_VACACIONES) VALUES ('00236','Cláudia Morais','2013-09-17',0.08,1);

INSERT INTO TABLA_DE_VENDEDORES
(MATRICULA, NOMBRE, FECHA_ADMISION, PORCENTAJE_COMISION, DE_VACACIONES) VALUES ('00238','Pericles Alves','2016-08-21',0.11,0);