SELECT * FROM tbcliente;

SELECT * FROM tbcliente WHERE FECHA_NACIMIENTO = '1995-01-13';
SELECT * FROM tbcliente WHERE FECHA_NACIMIENTO < '1995-01-13';
SELECT * FROM tbcliente WHERE FECHA_NACIMIENTO >= '1995-01-13';
SELECT * FROM tbcliente WHERE YEAR(FECHA_NACIMIENTO) = 1995;
SELECT * FROM tbcliente WHERE DAY(FECHA_NACIMIENTO) = 20;